[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
itertools = "0.14.0"
nom = "8.0.0"
phf = { version = "0.13.1", features = ["macros"] }
regex = "1.12.2"
